apiVersion: v1
kind: Service
metadata:
  name: order-summary-component
  namespace: default
spec:
  selector:
    app: order-summary-component-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
